name: "Test"
on:
  pull_request:
  push:
    branches:
      - "develop"
      - "feature/ci"

concurrency:
  group: ${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  checks:
    name: Flake Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          diagnostic-endpoint: ""
      - name: Enable Nix Store Caching
        uses: DeterminateSystems/magic-nix-cache-action@v2
        with:
          diagnostic-endpoint: ""
      - run: nix -L flake check --all-systems
      - run: nix -L flake check ./dev --all-systems

  packages:
    name: Build Packages
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          diagnostic-endpoint: ""
      - uses: DeterminateSystems/magic-nix-cache-action@v2
        with:
          diagnostic-endpoint: ""
      - uses: cachix/cachix-action@v13
        if: github.ref == 'refs/heads/develop'
        with:
          name: shanesveller-nix-beam-flakes
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: "./result"
          skipAddingSubstituter: true
      - run: nix -L build .#all
